/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.NguoiDungBUS;
import BUS.otpBUS;
import DTO.NguoiDungDTO;
import DTO.otpDTO;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDateTime;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Timer;
import java.util.TimerTask;
/**
 *
 * @author Admin
 */
public class DangKyAccount extends javax.swing.JFrame {
    ArrayList<otpDTO> dsotp = new ArrayList<>();
    ArrayList<NguoiDungDTO> dsnd = new ArrayList<>();
    DefaultTableModel model = new DefaultTableModel();
    static Timer t;
    public static int interval = 60;
    /**
     * Creates new form DangKyAccount
     */
    public DangKyAccount() {
        initComponents();
        jPanel1.setFocusable(true);
        jButton1.setEnabled(false);
        btnSubmit.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txthovaten = new javax.swing.JTextField();
        txtgmail = new javax.swing.JTextField();
        txtotp = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        sendOTP = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jpwmatkhau = new javax.swing.JPasswordField();
        jpwmatkhau2 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textTimer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("           Đăng ký ");
        jLabel5.setToolTipText("");

        txthovaten.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        txthovaten.setForeground(new java.awt.Color(153, 153, 153));
        txthovaten.setText("Họ và tên");
        txthovaten.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txthovatenFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txthovatenFocusLost(evt);
            }
        });
        txthovaten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthovatenActionPerformed(evt);
            }
        });

        txtgmail.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        txtgmail.setForeground(new java.awt.Color(153, 153, 153));
        txtgmail.setText("Gmail");
        txtgmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtgmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtgmailFocusLost(evt);
            }
        });

        txtotp.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        txtotp.setForeground(new java.awt.Color(153, 153, 153));
        txtotp.setText("OTP");
        txtotp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtotpFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtotpFocusLost(evt);
            }
        });

        btnSubmit.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnSubmit.setText("Đăng ký ngay");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        sendOTP.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        sendOTP.setText("Gửi Mã");
        sendOTP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sendOTPMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel1.setText("@gmail.com");

        jpwmatkhau.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jpwmatkhauFocusGained(evt);
            }
        });

        jpwmatkhau2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpwmatkhau2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Họ và Tên: ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Gmail: ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Mật khẩu: ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Nhập lại mật khẩu: ");

        textTimer.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
<<<<<<< HEAD
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
=======
                        .addComponent(txthovaten, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSubmit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
>>>>>>> master
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(textTimer, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
<<<<<<< HEAD
                                .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
=======
                                .addComponent(txtotp, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
>>>>>>> master
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sendOTP, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtgmail, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
<<<<<<< HEAD
                            .addComponent(jPasswordField1)
                            .addComponent(jPasswordField2))))
=======
                            .addComponent(jpwmatkhau)
                            .addComponent(jpwmatkhau2))))
>>>>>>> master
                .addGap(55, 55, 55))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txthovaten, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtgmail, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpwmatkhau, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpwmatkhau2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sendOTP, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
<<<<<<< HEAD
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textTimer, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
=======
                    .addComponent(txtotp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textTimer, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
>>>>>>> master
                .addContainerGap(88, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txthovatenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthovatenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthovatenActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
<<<<<<< HEAD
        if(jTextField5.getText() == "123123"){
            t.cancel();
        }
        textTimer.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        if (jTextField1.getText().trim().equals(""))
=======
        otpBUS bus = new otpBUS();
        otpDTO otp = new otpDTO();
        NguoiDungDTO nd = new NguoiDungDTO();
        NguoiDungBUS ndbus = new NguoiDungBUS();
        String a="Họ và tên";
        String b="Gmail";
        String c="";
//        if(!txthovaten.getText().equals(a) && !txtgmail.getText().equals(b) && !jpwmatkhau.getPassword().toString().equals(c) && jpwmatkhau.getPassword().toString().equals(jpwmatkhau2.getPassword().toString()) )
//        {
            if(bus.checkOTP(txtotp.getText(), txtgmail.getText()+"@gmail.com")==1)
            {
                nd.setName(txthovaten.getText());
                nd.setUsername(txtgmail.getText()+"@gmail.com");
                nd.setPassword(jpwmatkhau.getPassword().toString());
            
            ndbus.them(nd);
            dsnd.add(nd);
            t.cancel();  
            textTimer.setText("");
            }
            else
            {
                JOptionPane.showMessageDialog(null,"OTP nhập chưa chính xác");
            }
            
//        }
//        else
//        {
//            JOptionPane.showMessageDialog(null,"Vui lòng điền đầy đủ thông tin");
//        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void txthovatenFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txthovatenFocusLost
        if (txthovaten.getText().trim().equals(""))
>>>>>>> master
        {
            txthovaten.setText("Họ và tên");
            
        txthovaten.setForeground(new Color(153,153,153));
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txthovatenFocusLost

    private void txthovatenFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txthovatenFocusGained
        if(txthovaten.getText().trim().equals("Họ và tên"))
        {
            txthovaten.setText("");
        }
        txthovaten.setForeground(Color.black);
        // TODO add your handling code here:
    }//GEN-LAST:event_txthovatenFocusGained

    private void txtgmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtgmailFocusGained
        if(txtgmail.getText().trim().equals("Gmail"))
        {
            txtgmail.setText("");
        }
        txtgmail.setForeground(Color.black);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgmailFocusGained

    private void txtgmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtgmailFocusLost
    if (txtgmail.getText().trim().equals(""))
        {
            txtgmail.setText("Gmail");
            
        txtgmail.setForeground(new Color(153,153,153));
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgmailFocusLost

    private void txtotpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtotpFocusGained
        if(txtotp.getText().trim().equals("OTP"))
        {
            txtotp.setText("");
        }
        txtotp.setForeground(Color.black);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtotpFocusGained

    private void txtotpFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtotpFocusLost
        if (txtotp.getText().trim().equals(""))
        {
            txtotp.setText("OTP");
            
        txtotp.setForeground(new Color(153,153,153));
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtotpFocusLost

    private void jpwmatkhau2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpwmatkhau2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpwmatkhau2ActionPerformed

    private void jpwmatkhauFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jpwmatkhauFocusGained

        // TODO add your handling code here:
    }//GEN-LAST:event_jpwmatkhauFocusGained

    private void sendOTPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendOTPMouseClicked
        String a="Gmail";
        otpBUS bus = new otpBUS();
        otpDTO otp = new otpDTO();
        t = new Timer();
        if(txtgmail.getText().equals(a))
        {
            JOptionPane.showMessageDialog(null,"vui lòng nhập đầy đủ thông tin");
            
        }
        else {  
            otp.setGmail(txtgmail.getText()+"@gmail.com");
            //otp.setTime(LocalDateTime.now());
            if(bus.check(otp)==0)
            {
                JOptionPane.showMessageDialog(null,"Gmail đã tồn tại");
            }
            else
            {
                bus.them(otp);
                dsotp.add(otp);
                
                
            }
            t.scheduleAtFixedRate(new TimerTask() {
                public void run() {
                    System.out.println(interval);
                    textTimer.setText(String.valueOf(interval));
                    interval--;
                    if( interval < 0) 
                    {
                        String mail = txtgmail.getText()+"@gmail.com";
                        bus.xoa(mail);
                        t.cancel();
                    }
                    
                    if(txtotp.getText().length()==6){
                        btnSubmit.setEnabled(true);
                    }else if(txtotp.getText().length()!= 6){
                        btnSubmit.setEnabled(false);
                    }
                }
            }, 1000, 1000);
//            bus.them(otp);
        }
//        t= new Timer(10000, new ActionListener() {
//            @Override
//            public void actionPerformed(ActionEvent e) {
//                String mail = txtgmail.getText();
//                bus.xoa(mail);
//                t.stop();
//                
//            }
//        });
//        t.start();
<<<<<<< HEAD
        t = new Timer();
            t.scheduleAtFixedRate(new TimerTask() {

                public void run() {
                    System.out.println(interval);
                    textTimer.setText(String.valueOf(interval));
                    interval--;
                    if( interval < 0) t.cancel();

                    
                    if(jTextField5.getText().length()==6){
                        jButton1.setEnabled(true);
                    }else if(jTextField5.getText().length()!= 6){
                        jButton1.setEnabled(false);
                    }
                }
            }, 1000, 1000);
=======
        
        
>>>>>>> master
        
        // TODO add your handling code here:
    }//GEN-LAST:event_sendOTPMouseClicked
//        private static final int setInterval() {
//        if (interval == 1)
//            t.cancel();
//        return --interval;
//        }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangKyAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangKyAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangKyAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangKyAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DangKyAccount().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jpwmatkhau;
    private javax.swing.JPasswordField jpwmatkhau2;
    private javax.swing.JButton sendOTP;
    public static javax.swing.JLabel textTimer;
    private javax.swing.JTextField txtgmail;
    private javax.swing.JTextField txthovaten;
    private javax.swing.JTextField txtotp;
    // End of variables declaration//GEN-END:variables
}
