/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import static GUI.TaoCauHoiJPanel.jComboBox1;
import static Server.Client.SendToServer;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Admin
 */
public class MainJFrame extends javax.swing.JFrame {
    public static MainJFrame INTANCEMAINJFRAME =null;
    public static MainJFrame getIntanceMainJFrame (){
        if(INTANCEMAINJFRAME == null) INTANCEMAINJFRAME = new MainJFrame();
        return INTANCEMAINJFRAME;
    }
    public static void CloseMainJFrame (){
        if(INTANCEMAINJFRAME == null) return;
        INTANCEMAINJFRAME.dispose();
    }
    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        setTitle("QUẢN LÝ ĐỀ THI TRẮC NGHIỆM");
        
        ChuyenManHinhController controller = new ChuyenManHinhController(jpnView);
        controller.setView(jpnAccount, jlbAccount);
        
        List<DanhMuc> listItem = new ArrayList<>();
        listItem.add(new DanhMuc("Account",jpnAccount,jlbAccount));
        listItem.add(new DanhMuc("DeThi",jpnDeThi,jlbDeThi));
        listItem.add(new DanhMuc("TaoCauHoi",jpnCauHoi,jlbCauHoi));
        listItem.add(new DanhMuc("ThiThu",jpnThiThu,jlbThiThu));
        listItem.add(new DanhMuc("ThanhTich",jpnThanhTich,jlbThanhTich));
        
        controller.setEvent(listItem);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnRoot = new javax.swing.JPanel();
        jpnMenu = new javax.swing.JPanel();
        jpnTrangChu = new javax.swing.JPanel();
        jlbTrangChu = new javax.swing.JLabel();
        jpnAccount = new javax.swing.JPanel();
        jlbAccount = new javax.swing.JLabel();
        jpnDeThi = new javax.swing.JPanel();
        jlbDeThi = new javax.swing.JLabel();
        jpnCauHoi = new javax.swing.JPanel();
        jlbCauHoi = new javax.swing.JLabel();
        jpnThiThu = new javax.swing.JPanel();
        jlbThiThu = new javax.swing.JLabel();
        jpnThanhTich = new javax.swing.JPanel();
        jlbThanhTich = new javax.swing.JLabel();
        jpnView = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpnMenu.setBackground(new java.awt.Color(82, 83, 81));

        jpnTrangChu.setBackground(new java.awt.Color(232, 64, 60));

        jlbTrangChu.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlbTrangChu.setForeground(new java.awt.Color(255, 255, 255));
        jlbTrangChu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbTrangChu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/baseline_import_contacts_white_24dp_1.png"))); // NOI18N
        jlbTrangChu.setText("QUẢN LÝ ĐỀ THI TRẮC NGHIỆM");

        javax.swing.GroupLayout jpnTrangChuLayout = new javax.swing.GroupLayout(jpnTrangChu);
        jpnTrangChu.setLayout(jpnTrangChuLayout);
        jpnTrangChuLayout.setHorizontalGroup(
            jpnTrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTrangChuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbTrangChu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnTrangChuLayout.setVerticalGroup(
            jpnTrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnTrangChuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbTrangChu, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpnAccount.setBackground(new java.awt.Color(76, 175, 80));

        jlbAccount.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jlbAccount.setForeground(new java.awt.Color(255, 255, 255));
        jlbAccount.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlbAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/baseline_person_white_24dp.png"))); // NOI18N
        jlbAccount.setText("Thông Tin Người Dùng");

        javax.swing.GroupLayout jpnAccountLayout = new javax.swing.GroupLayout(jpnAccount);
        jpnAccount.setLayout(jpnAccountLayout);
        jpnAccountLayout.setHorizontalGroup(
            jpnAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnAccountLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnAccountLayout.setVerticalGroup(
            jpnAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnAccountLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbAccount, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpnDeThi.setBackground(new java.awt.Color(76, 175, 80));

        jlbDeThi.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jlbDeThi.setForeground(new java.awt.Color(255, 255, 255));
        jlbDeThi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlbDeThi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/baseline_import_contacts_white_24dp_1.png"))); // NOI18N
        jlbDeThi.setText("Tạo Đề Thi");

        javax.swing.GroupLayout jpnDeThiLayout = new javax.swing.GroupLayout(jpnDeThi);
        jpnDeThi.setLayout(jpnDeThiLayout);
        jpnDeThiLayout.setHorizontalGroup(
            jpnDeThiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnDeThiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbDeThi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnDeThiLayout.setVerticalGroup(
            jpnDeThiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnDeThiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbDeThi, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpnCauHoi.setBackground(new java.awt.Color(76, 175, 80));

        jlbCauHoi.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jlbCauHoi.setForeground(new java.awt.Color(255, 255, 255));
        jlbCauHoi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlbCauHoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/outline_create_white_18dp.png"))); // NOI18N
        jlbCauHoi.setText("Tạo Câu Hỏi");
        jlbCauHoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbCauHoiMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpnCauHoiLayout = new javax.swing.GroupLayout(jpnCauHoi);
        jpnCauHoi.setLayout(jpnCauHoiLayout);
        jpnCauHoiLayout.setHorizontalGroup(
            jpnCauHoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnCauHoiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbCauHoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnCauHoiLayout.setVerticalGroup(
            jpnCauHoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnCauHoiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbCauHoi, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpnThiThu.setBackground(new java.awt.Color(76, 175, 80));

        jlbThiThu.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jlbThiThu.setForeground(new java.awt.Color(255, 255, 255));
        jlbThiThu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlbThiThu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/outline_assignment_white_24dp.png"))); // NOI18N
        jlbThiThu.setText("Thi Thử");

        javax.swing.GroupLayout jpnThiThuLayout = new javax.swing.GroupLayout(jpnThiThu);
        jpnThiThu.setLayout(jpnThiThuLayout);
        jpnThiThuLayout.setHorizontalGroup(
            jpnThiThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnThiThuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbThiThu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnThiThuLayout.setVerticalGroup(
            jpnThiThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnThiThuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbThiThu, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpnThanhTich.setBackground(new java.awt.Color(76, 175, 80));
        jpnThanhTich.setPreferredSize(new java.awt.Dimension(0, 100));

        jlbThanhTich.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jlbThanhTich.setForeground(new java.awt.Color(255, 255, 255));
        jlbThanhTich.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlbThanhTich.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/baseline_star_rate_white_24dp.png"))); // NOI18N
        jlbThanhTich.setText("Thành tích");

        javax.swing.GroupLayout jpnThanhTichLayout = new javax.swing.GroupLayout(jpnThanhTich);
        jpnThanhTich.setLayout(jpnThanhTichLayout);
        jpnThanhTichLayout.setHorizontalGroup(
            jpnThanhTichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnThanhTichLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbThanhTich, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnThanhTichLayout.setVerticalGroup(
            jpnThanhTichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnThanhTichLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbThanhTich, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jpnMenuLayout = new javax.swing.GroupLayout(jpnMenu);
        jpnMenu.setLayout(jpnMenuLayout);
        jpnMenuLayout.setHorizontalGroup(
            jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnTrangChu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpnMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnDeThi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnCauHoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnThiThu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnThanhTich, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpnMenuLayout.setVerticalGroup(
            jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnMenuLayout.createSequentialGroup()
                .addComponent(jpnTrangChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpnDeThi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpnCauHoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpnThiThu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpnThanhTich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpnViewLayout = new javax.swing.GroupLayout(jpnView);
        jpnView.setLayout(jpnViewLayout);
        jpnViewLayout.setHorizontalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 917, Short.MAX_VALUE)
        );
        jpnViewLayout.setVerticalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpnRootLayout = new javax.swing.GroupLayout(jpnRoot);
        jpnRoot.setLayout(jpnRootLayout);
        jpnRootLayout.setHorizontalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnRootLayout.createSequentialGroup()
                .addComponent(jpnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnRootLayout.setVerticalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnRootLayout.createSequentialGroup()
                .addGroup(jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlbCauHoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbCauHoiMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jlbCauHoiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IllegalAccessException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }
    public static void Run(){
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }
    public static void AlertMessageFromServer(String str){
        showMessageDialog(null,str, "Message from server", JOptionPane.PLAIN_MESSAGE);
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlbAccount;
    private javax.swing.JLabel jlbCauHoi;
    private javax.swing.JLabel jlbDeThi;
    private javax.swing.JLabel jlbThanhTich;
    private javax.swing.JLabel jlbThiThu;
    private javax.swing.JLabel jlbTrangChu;
    private javax.swing.JPanel jpnAccount;
    private javax.swing.JPanel jpnCauHoi;
    private javax.swing.JPanel jpnDeThi;
    private javax.swing.JPanel jpnMenu;
    private javax.swing.JPanel jpnRoot;
    private javax.swing.JPanel jpnThanhTich;
    private javax.swing.JPanel jpnThiThu;
    private javax.swing.JPanel jpnTrangChu;
    private javax.swing.JPanel jpnView;
    // End of variables declaration//GEN-END:variables
}
